import { applePhoneImages, imageAt } from "@/lib/catalogImages";

type AppleGadget = {
  id: string;
  name: string;
  model: string;
  storage: string | null;
  price: string;
  image: string;
};

const appleGadgets: AppleGadget[] = [
  {
    id: "iphone-16-pro",
    name: "iPhone 16 Pro",
    model: "iPhone 16 Pro",
    storage: "256 GB",
    price: "N 2,250,000",
    image: "/apple/iphone-16-pro.webp",
  },
  {
    id: "iphone-16",
    name: "iPhone 16",
    model: "iPhone 16",
    storage: "128 GB",
    price: "N 1,650,000",
    image: "/apple/iphone-16.webp",
  },
  {
    id: "iphone-16e",
    name: "iPhone 16e",
    model: "iPhone 16e",
    storage: "128 GB",
    price: "N 1,250,000",
    image: "/apple/iphone-16e.webp",
  },
  {
    id: "iphone-15-pro",
    name: "iPhone 15 Pro",
    model: "iPhone 15 Pro",
    storage: "256 GB",
    price: "N 1,980,000",
    image: imageAt(applePhoneImages, 1),
  },
  {
    id: "iphone-15",
    name: "iPhone 15",
    model: "iPhone 15",
    storage: "128 GB",
    price: "N 1,420,000",
    image: imageAt(applePhoneImages, 2),
  },
  {
    id: "iphone-15-plus",
    name: "iPhone 15 Plus",
    model: "iPhone 15 Plus",
    storage: "256 GB",
    price: "N 1,560,000",
    image: imageAt(applePhoneImages, 3),
  },
  {
    id: "iphone-14-pro",
    name: "iPhone 14 Pro",
    model: "iPhone 14 Pro",
    storage: "256 GB",
    price: "N 1,720,000",
    image: imageAt(applePhoneImages, 4),
  },
  {
    id: "iphone-14",
    name: "iPhone 14",
    model: "iPhone 14",
    storage: "128 GB",
    price: "N 1,180,000",
    image: imageAt(applePhoneImages, 5),
  },
  {
    id: "iphone-13",
    name: "iPhone 13",
    model: "iPhone 13",
    storage: "128 GB",
    price: "N 920,000",
    image: imageAt(applePhoneImages, 6),
  },
  {
    id: "iphone-13-mini",
    name: "iPhone 13 mini",
    model: "iPhone 13 mini",
    storage: "128 GB",
    price: "N 780,000",
    image: imageAt(applePhoneImages, 7),
  },
  {
    id: "iphone-12-gbg-1",
    name: "iPhone 12",
    model: "iPhone 12",
    storage: null,
    price: "N 780,000",
    image: "/products/iphone 12 Gbg 1.webp",
  },
  {
    id: "iphone-12promax-124gbg-1",
    name: "iPhone 12 Pro Max",
    model: "iPhone 12 Pro Max",
    storage: "124gbg",
    price: "N 1,050,000",
    image: "/products/iphone 12promax 124gbg 1.webp",
  },
  {
    id: "iphone-x-256-gbgb-1",
    name: "iPhone X",
    model: "iPhone X",
    storage: "256 Gbgb",
    price: "N 460,000",
    image: "/products/Iphone X 256 Gbgb 1.webp",
  },
  {
    id: "iphone-xsmax-256gbg-1",
    name: "iPhone Xs Max",
    model: "iPhone Xs Max",
    storage: "256gbg",
    price: "N 540,000",
    image: "/products/iphone Xsmax 256gbg 1.webp",
  },
  {
    id: "iphone-xsmax-64-ggbg-1",
    name: "iPhone Xs Max",
    model: "iPhone Xs Max",
    storage: "64 Ggbg",
    price: "N 500,000",
    image: "/products/iphone Xsmax 64 Ggbg 1.webp",
  },
  {
    id: "apple-line-21",
    name: "Apple iPhone Line 21",
    model: "Edition 21",
    storage: null,
    price: "N 720000",
    image: "/apple/iphone-16-pro.webp",
  },
  {
    id: "apple-line-22",
    name: "Apple iPhone Line 22",
    model: "Edition 22",
    storage: null,
    price: "N 738000",
    image: "/apple/iphone-16.webp",
  },
  {
    id: "apple-line-23",
    name: "Apple iPhone Line 23",
    model: "Edition 23",
    storage: null,
    price: "N 756000",
    image: "/apple/iphone-16e.webp",
  },
  {
    id: "apple-line-24",
    name: "Apple iPhone Line 24",
    model: "Edition 24",
    storage: null,
    price: "N 774000",
    image: "/products/iphone 12 Gbg 1.webp",
  },
  {
    id: "apple-line-25",
    name: "Apple iPhone Line 25",
    model: "Edition 25",
    storage: null,
    price: "N 792000",
    image: "/products/iphone 12promax 124gbg 1.webp",
  },
  {
    id: "apple-line-26",
    name: "Apple iPhone Line 26",
    model: "Edition 26",
    storage: null,
    price: "N 810000",
    image: "/products/Iphone X 256 Gbgb 1.webp",
  },
  {
    id: "apple-line-27",
    name: "Apple iPhone Line 27",
    model: "Edition 27",
    storage: null,
    price: "N 828000",
    image: "/products/iphone Xsmax 256gbg 1.webp",
  },
  {
    id: "apple-line-28",
    name: "Apple iPhone Line 28",
    model: "Edition 28",
    storage: null,
    price: "N 846000",
    image: "/products/iphone Xsmax 64 Ggbg 1.webp",
  },
  {
    id: "apple-line-29",
    name: "Apple iPhone Line 29",
    model: "Edition 29",
    storage: null,
    price: "N 864000",
    image: "/apple/iphone-16-pro.webp",
  },
  {
    id: "apple-line-30",
    name: "Apple iPhone Line 30",
    model: "Edition 30",
    storage: null,
    price: "N 882000",
    image: "/apple/iphone-16.webp",
  },
];

export { appleGadgets };
export type { AppleGadget };
