import { imageAt, samsungPhoneImages } from "@/lib/catalogImages";

type SamsungGadget = {
  id: string;
  name: string;
  model: string;
  storage: string | null;
  price: string;
  image: string;
};

const samsungGadgets: SamsungGadget[] = [
  {
    id: "galaxy-s24-fe",
    name: "Samsung Galaxy S24 FE",
    model: "Galaxy S24 FE",
    storage: "256 GB",
    price: "N 1,180,000",
    image: "/samsung/galaxy-s24-fe.gif",
  },
  {
    id: "galaxy-s25-series",
    name: "Samsung Galaxy S25 Series",
    model: "Galaxy S25 Series",
    storage: "256 GB",
    price: "N 1,780,000",
    image: "/samsung/galaxy-s25-series.webp",
  },
  {
    id: "galaxy-s25-fe",
    name: "Samsung Galaxy S25 FE",
    model: "Galaxy S25 FE",
    storage: "256 GB",
    price: "N 1,420,000",
    image: "/samsung/galaxy-s25-fe.webp",
  },
  {
    id: "galaxy-s26-series",
    name: "Samsung Galaxy S26 Series",
    model: "Galaxy S26 Series",
    storage: "512 GB",
    price: "N 2,050,000",
    image: "/samsung/galaxy-s26-series.webp",
  },
  {
    id: "galaxy-note-10-plus-1",
    name: "Samsung Galaxy Note 10+",
    model: "Galaxy Note 10+",
    storage: null,
    price: "N 420,000",
    image: "/products/Galaxy Note 10+ 1.webp",
  },
  {
    id: "galaxy-note-9-1",
    name: "Samsung Galaxy Note 9",
    model: "Galaxy Note 9",
    storage: null,
    price: "N 350,000",
    image: "/products/Galaxy Note 9 1.webp",
  },
  {
    id: "samsung-a03-1",
    name: "Samsung A03",
    model: "Samsung A03",
    storage: null,
    price: "N 145,000",
    image: "/products/Samsung A03 1.webp",
  },
  {
    id: "samsung-s10-1",
    name: "Samsung S10",
    model: "Samsung S10",
    storage: null,
    price: "N 310,000",
    image: "/products/Samsung S10 1.webp",
  },
  {
    id: "galaxy-z-fold-6",
    name: "Samsung Galaxy Z Fold 6",
    model: "Galaxy Z Fold 6",
    storage: "512 GB",
    price: "N 2,280,000",
    image: imageAt(samsungPhoneImages, 1),
  },
  {
    id: "galaxy-z-flip-6",
    name: "Samsung Galaxy Z Flip 6",
    model: "Galaxy Z Flip 6",
    storage: "256 GB",
    price: "N 1,350,000",
    image: imageAt(samsungPhoneImages, 2),
  },
  {
    id: "galaxy-a55",
    name: "Samsung Galaxy A55",
    model: "Galaxy A55",
    storage: "128 GB",
    price: "N 385,000",
    image: imageAt(samsungPhoneImages, 3),
  },
  {
    id: "galaxy-a35",
    name: "Samsung Galaxy A35",
    model: "Galaxy A35",
    storage: "128 GB",
    price: "N 295,000",
    image: imageAt(samsungPhoneImages, 4),
  },
  {
    id: "galaxy-s23-fe",
    name: "Samsung Galaxy S23 FE",
    model: "Galaxy S23 FE",
    storage: "256 GB",
    price: "N 980,000",
    image: imageAt(samsungPhoneImages, 5),
  },
  {
    id: "galaxy-m55",
    name: "Samsung Galaxy M55",
    model: "Galaxy M55",
    storage: "256 GB",
    price: "N 410,000",
    image: imageAt(samsungPhoneImages, 6),
  },
  {
    id: "galaxy-f55",
    name: "Samsung Galaxy F55",
    model: "Galaxy F55",
    storage: "256 GB",
    price: "N 365,000",
    image: imageAt(samsungPhoneImages, 7),
  },
  {
    id: "galaxy-xcover-7",
    name: "Samsung Galaxy XCover 7",
    model: "Galaxy XCover 7",
    storage: "128 GB",
    price: "N 520,000",
    image: imageAt(samsungPhoneImages, 8),
  },
  {
    id: "samsung-line-21",
    name: "Samsung Galaxy Line 21",
    model: "Galaxy 21",
    storage: null,
    price: "N 320000",
    image: "/products/Samsung S10 1.webp",
  },
  {
    id: "samsung-line-22",
    name: "Samsung Galaxy Line 22",
    model: "Galaxy 22",
    storage: null,
    price: "N 335000",
    image: "/products/Galaxy Note 9 1.webp",
  },
  {
    id: "samsung-line-23",
    name: "Samsung Galaxy Line 23",
    model: "Galaxy 23",
    storage: null,
    price: "N 350000",
    image: "/products/Galaxy Note 10+ 1.webp",
  },
  {
    id: "samsung-line-24",
    name: "Samsung Galaxy Line 24",
    model: "Galaxy 24",
    storage: null,
    price: "N 365000",
    image: "/samsung/galaxy-s24-fe.gif",
  },
  {
    id: "samsung-line-25",
    name: "Samsung Galaxy Line 25",
    model: "Galaxy 25",
    storage: null,
    price: "N 380000",
    image: "/samsung/galaxy-s25-series.webp",
  },
  {
    id: "samsung-line-26",
    name: "Samsung Galaxy Line 26",
    model: "Galaxy 26",
    storage: null,
    price: "N 395000",
    image: "/samsung/galaxy-s26-series.webp",
  },
  {
    id: "samsung-line-27",
    name: "Samsung Galaxy Line 27",
    model: "Galaxy 27",
    storage: null,
    price: "N 410000",
    image: "/products/Samsung A03 1.webp",
  },
  {
    id: "samsung-line-28",
    name: "Samsung Galaxy Line 28",
    model: "Galaxy 28",
    storage: null,
    price: "N 425000",
    image: "/products/Samsung S10 1.webp",
  },
  {
    id: "samsung-line-29",
    name: "Samsung Galaxy Line 29",
    model: "Galaxy 29",
    storage: null,
    price: "N 440000",
    image: "/samsung/galaxy-s25-fe.webp",
  },
  {
    id: "samsung-line-30",
    name: "Samsung Galaxy Line 30",
    model: "Galaxy 30",
    storage: null,
    price: "N 455000",
    image: "/samsung/galaxy-s26-series.webp",
  },
];

export { samsungGadgets };
export type { SamsungGadget };
